### ISSUE TITLE
npm install breaking because of python

### ISSUE THREAD

**Issue by KenWuqianghao** [parksb/handmade-blog#48]
I'm on a M1 Mac, and I receive this error when trying to npm install. Python 3.9 is available.
```

npm ERR! code 1
npm ERR! path /Users/kenwu/Documents/blog/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.0.0 | darwin | arm64
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/kenwu/Documents/blog/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/kenwu/Documents/blog/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/kenwu/Documents/blog/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/kenwu/Documents/blog/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/kenwu/Documents/blog/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/kenwu/Documents/blog/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/kenwu/Documents/blog/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:203:21)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/18.0.0/bin/node" "/Users/kenwu/Documents/blog/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/kenwu/Documents/blog/node_modules/deasync
npm ERR! gyp ERR! node -v v18.0.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed
```

**Comment by parksb** [comment]
I just removed packages that depend on node-gyp. Could you try again on the latest version? You're gonna have to start with the first step (clicking the 'Use this template' button)

**Comment by KenWuqianghao** [comment]
Nice, solved. ty
